version: 2

updates:
  - package-ecosystem: pip
    directory: /test-repo/
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    groups:
      actions:
        patterns:
          - "*"
    directories:
        - "/"
        - "{{cookiecutter.project_slug}}"
    schedule:
      interval: daily